<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><style>
@page{margin:0}*{box-sizing:border-box}body{margin:0;color:#111;font-family:DejaVu Sans,sans-serif}.page{width:210mm;height:297mm;position:relative;page-break-after:always;overflow:hidden}.page:last-child{page-break-after:auto}.background{position:absolute;top:0;left:0;width:210mm;height:297mm}.field{position:absolute;z-index:2;height:2.5%;font-size:8.2pt;line-height:1;white-space:nowrap;overflow:hidden;padding:3mm 1.3mm 0}.field.small{font-size:7.2pt}.field.center{text-align:center}.witness-field{padding-top:1.7mm}.signature{position:absolute;z-index:2;object-fit:contain}.drawn-signature{width:auto!important;height:5.2%!important}.witness-signature{width:auto!important;height:4.4%!important}.pastor-signature{width:12%!important;height:8%!important}.mark{position:absolute;z-index:3;font-size:11pt;font-weight:bold;line-height:1}
</style></head><body>
@php
$fmtData=fn($v)=>$v?\Carbon\Carbon::parse($v)->format('d/m/Y'):'';
$fmtCpf=function($v){$n=preg_replace('/\D+/','',(string)$v);return strlen($n)===11?substr($n,0,3).'.'.substr($n,3,3).'.'.substr($n,6,3).'-'.substr($n,9,2):$v;};
$estadoCivil=fn($v)=>match($v){'solteiro'=>'Solteiro(a)','casado'=>'Casado(a)','divorciado'=>'Divorciado(a)','viuvo'=>'Viúvo(a)','uniao_estavel'=>'União estável',default=>$v};
$meses=[1=>'janeiro',2=>'fevereiro',3=>'março',4=>'abril',5=>'maio',6=>'junho',7=>'julho',8=>'agosto',9=>'setembro',10=>'outubro',11=>'novembro',12=>'dezembro'];
@endphp
@foreach($documentos as $documento)
@php
$aceite=$documento['aceite'];$d=data_get($aceite->dados_snapshot,'cadastro',[]);$r=data_get($aceite->dados_snapshot,'responsavel_legal');
$nascimento=data_get($d,'data_nascimento',$pessoa->data_nascimento);$idade=$nascimento?\Carbon\Carbon::parse($nascimento)->age:null;$menor=(bool)data_get($aceite->dados_snapshot,'menor_de_idade',false);
$cidade=$pessoa->cidade->nome??'';$uf=$pessoa->estado->uf??'';$igreja=$pessoa->igreja->nome??'';$enderecoIgreja=data_get($d,'endereco_igreja',$pessoa->endereco_igreja);
$endereco=trim(data_get($d,'endereco',$pessoa->endereco).' '.data_get($d,'numero',$pessoa->numero).', '.data_get($d,'bairro',$pessoa->bairro).', '.$cidade.' - '.$uf.', CEP '.data_get($d,'cep',$pessoa->cep));
$dataAssinatura=$aceite->aceito_em??now();$local=$cidade?:'Salvador';
@endphp
@foreach($documento['paginas'] as $indice=>$pagina)
<section class="page termo-{{ $aceite->tipo }} pagina-{{ $indice+1 }}"><img class="background" src="{{ $pagina }}" alt="Página do termo">
@if($aceite->tipo==='adesao_servico_voluntario'&&$indice===0)
<span class="field" style="left:23%;top:16.05%;width:19.2%">{{ $enderecoIgreja }}</span><span class="field center" style="left:44.3%;top:16.05%;width:49%">{{ data_get($d,'nome',$pessoa->nome) }}</span>
<span class="field center" style="left:16.5%;top:19.15%;width:13.7%">{{ $fmtData($nascimento) }}</span><span class="field center" style="left:37.4%;top:19.15%;width:23%">{{ $fmtCpf(data_get($d,'cpf',$pessoa->cpf)) }}</span><span class="field center" style="left:70.3%;top:19.15%;width:23.2%">{{ data_get($d,'rg',$pessoa->rg) }}</span>
<span class="field small" style="left:28.5%;top:22.25%;width:64.8%">{{ data_get($d,'endereco',$pessoa->endereco) }}</span><span class="field center" style="left:8.1%;top:25.35%;width:16%">{{ data_get($d,'numero',$pessoa->numero) }}</span><span class="field center" style="left:29.7%;top:25.35%;width:30.5%">{{ data_get($d,'bairro',$pessoa->bairro) }}</span><span class="field center" style="left:65.5%;top:25.35%;width:19%">{{ data_get($d,'cep',$pessoa->cep) }}</span><span class="field center" style="left:87.7%;top:25.35%;width:5.6%">{{ $uf }}</span><span class="field small" style="left:46.5%;top:34.7%;width:46.5%">{{ $enderecoIgreja }}</span>
@elseif($aceite->tipo==='adesao_servico_voluntario'&&$indice===1)
<span class="field center" style="left:34.2%;top:16.45%;width:22.5%">{{ $local }}</span><span class="field center" style="left:57.8%;top:16.45%;width:6.2%">{{ $dataAssinatura->format('d') }}</span><span class="field center" style="left:67.4%;top:16.45%;width:16.7%">{{ $meses[(int)$dataAssinatura->format('n')] }}</span><span class="field center" style="left:87.3%;top:16.45%;width:6%">{{ $dataAssinatura->format('Y') }}</span><img class="signature drawn-signature" src="{{ $assinaturaVoluntario }}" style="left:39%;top:19.7%"><img class="signature pastor-signature" src="{{ $assinaturaPastor }}" style="left:44%;top:25.5%"><span class="field witness-field" style="left:12%;top:38.75%;width:81.5%">{{ data_get($d,'testemunha_nome',$pessoa->testemunha_nome) }}</span><span class="field witness-field" style="left:15.5%;top:42.75%;width:78%">{{ data_get($d,'testemunha_rg',$pessoa->testemunha_rg) }}</span><img class="signature witness-signature" src="{{ $assinaturaTestemunha }}" style="left:39%;top:46.2%">
@elseif($aceite->tipo==='cessao_imagem_voz'&&$indice===0)
<span class="field" style="left:20.4%;top:20.05%;width:73.5%">{{ data_get($d,'nome',$pessoa->nome) }}</span><span class="field" style="left:18.8%;top:23.5%;width:29.5%">{{ data_get($d,'nacionalidade',$pessoa->nacionalidade) }}</span><span class="field" style="left:64.7%;top:23.5%;width:22%">{{ $estadoCivil(data_get($d,'estado_civil',$pessoa->estado_civil)) }}</span><span class="field" style="left:14.4%;top:26.9%;width:79.5%">{{ data_get($d,'profissao',$pessoa->profissao) }}</span><span class="field" style="left:9.3%;top:30.25%;width:27%">{{ data_get($d,'rg',$pessoa->rg) }}</span><span class="field" style="left:46.3%;top:30.25%;width:26.5%">{{ $fmtCpf(data_get($d,'cpf',$pessoa->cpf)) }}</span><span class="field small" style="left:6%;top:35.7%;width:87.8%">{{ $endereco }}</span><span class="field center" style="left:23.5%;top:42.65%;width:19%">{{ $fmtData($nascimento) }}</span><span class="field center" style="left:48.7%;top:42.65%;width:5.5%">{{ $idade }}</span><span class="mark" style="left:80.15%;top:43.35%">{{ $menor?'X':'' }}</span><span class="mark" style="left:88.65%;top:43.35%">{{ $menor?'':'X' }}</span>
@if($r) @php $rn=data_get($r,'data_nascimento');$ri=$rn?\Carbon\Carbon::parse($rn)->age:'';$re=trim(data_get($r,'endereco').' '.data_get($r,'numero').', '.data_get($r,'bairro').', CEP '.data_get($r,'cep')); @endphp
<span class="field" style="left:20.4%;top:58.25%;width:73.5%">{{ data_get($r,'nome') }}</span><span class="field" style="left:18.8%;top:61.65%;width:29.5%">{{ data_get($r,'nacionalidade') }}</span><span class="field" style="left:64.7%;top:61.65%;width:22%">{{ $estadoCivil(data_get($r,'estado_civil')) }}</span><span class="field" style="left:14.4%;top:65.05%;width:77%">{{ data_get($r,'profissao') }}</span><span class="field" style="left:9.3%;top:68.4%;width:27%">{{ data_get($r,'rg') }}</span><span class="field" style="left:46.3%;top:68.4%;width:26.5%">{{ $fmtCpf(data_get($r,'cpf')) }}</span><span class="field small" style="left:6%;top:73.9%;width:87.8%">{{ $re }}</span><span class="field center" style="left:23.5%;top:80.8%;width:19%">{{ $fmtData($rn) }}</span><span class="field center" style="left:48.7%;top:80.8%;width:5.5%">{{ $ri }}</span>@endif
@elseif($aceite->tipo==='cessao_imagem_voz'&&$indice===3)
<span class="field center" style="left:33.3%;top:58.2%;width:22.5%">{{ $local }}</span><span class="field center" style="left:57%;top:58.2%;width:6.4%">{{ $dataAssinatura->format('d') }}</span><span class="field center" style="left:66.8%;top:58.2%;width:17%">{{ $meses[(int)$dataAssinatura->format('n')] }}</span><span class="field center" style="left:87.3%;top:58.2%;width:6%">{{ $dataAssinatura->format('Y') }}</span><img class="signature drawn-signature" src="{{ $assinaturaVoluntario }}" style="left:16%;top:69.2%"><span class="field center small" style="left:6%;top:72.1%;width:41.5%">{{ data_get($d,'nome',$pessoa->nome) }}</span><img class="signature pastor-signature" src="{{ $assinaturaPastor }}" style="left:66%;top:67.8%"><span class="field center small" style="left:50.5%;top:72.1%;width:43%">{{ data_get($pastor,'nome') }}</span>
@elseif($aceite->tipo==='utilizacao_uniforme'&&$indice===0)
<span class="field" style="left:59.8%;top:13.35%;width:33.5%">{{ $enderecoIgreja }}</span><span class="field center" style="left:7.5%;top:16.65%;width:55.4%">{{ data_get($d,'nome',$pessoa->nome) }}</span><span class="field center" style="left:73.5%;top:16.65%;width:19.8%">{{ $fmtData($nascimento) }}</span><span class="field center" style="left:40%;top:20%;width:17.2%">{{ data_get($d,'rg',$pessoa->rg) }}</span><span class="field center" style="left:73.5%;top:20%;width:19.8%">{{ $fmtCpf(data_get($d,'cpf',$pessoa->cpf)) }}</span><span class="field small" style="left:29%;top:23.3%;width:53%">{{ data_get($d,'endereco',$pessoa->endereco) }}</span><span class="field center" style="left:85.5%;top:23.3%;width:7.8%">{{ data_get($d,'numero',$pessoa->numero) }}</span><span class="field" style="left:18.5%;top:26.65%;width:34.2%">{{ data_get($d,'complemento',$pessoa->complemento) }}</span><span class="field" style="left:59%;top:26.65%;width:34.3%">{{ data_get($d,'bairro',$pessoa->bairro) }}</span><span class="field center" style="left:10.3%;top:30%;width:16.8%">{{ data_get($d,'cep',$pessoa->cep) }}</span><span class="field center" style="left:34.4%;top:30%;width:30.3%">{{ $cidade }}</span><span class="field center" style="left:68%;top:30%;width:5.5%">{{ $uf }}</span><span class="field center" style="left:33.8%;top:69.55%;width:22.5%">{{ $local }}</span><span class="field center" style="left:57.5%;top:69.55%;width:6.5%">{{ $dataAssinatura->format('d') }}</span><span class="field center" style="left:67.5%;top:69.55%;width:16.5%">{{ $meses[(int)$dataAssinatura->format('n')] }}</span><span class="field center" style="left:87.3%;top:69.55%;width:6%">{{ $dataAssinatura->format('Y') }}</span><img class="signature drawn-signature" src="{{ $assinaturaVoluntario }}" style="left:16%;top:75%"><img class="signature pastor-signature" src="{{ $assinaturaPastor }}" style="left:66%;top:73.7%"><span class="field center small" style="left:51.4%;top:83.75%;width:42.4%">{{ $igreja }}</span>
@endif
</section>
@endforeach
@endforeach
</body></html>
